"""empty message

Revision ID: 24eafdc2d31a
Revises: 5c7b6b15ca3b
Create Date: 2023-08-14 11:57:04.438418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24eafdc2d31a"
down_revision: Union[str, None] = "5c7b6b15ca3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
